// All user-visible Chinese strings live here. Animations MUST NOT hard-code
// Chinese inline — add the string here and import it. Seeded from
// PROJECT_PLAN.md section 10; expand per chapter as animations land.

export const labels = {
  common: {
    altitude:   '高度',
    velocity:   '速度',
    thrust:     '推力',
    attitude:   '姿态',
    position:   '位置',
    error:      '误差',
    mode:       '模式',
    frequency:  '频率',
    on:         '开启',
    off:        '关闭',
  },
  layers: {
    hardware:     '硬件层',
    control:      '控制层',
    localization: '定位层',
    planning:     '规划层',
    perception:   '感知层',
    coordination: '协同层',
  },
  ch01: {
    stackTitle:    '自主飞行技术栈',
    pyramidTitle:  '频率金字塔',
    couplingTitle: '模块耦合',
    stack: {
      layersPanel:  '层级 · 频率',
      flowPanel:    '数据流',
      activeLayer:  '当前层',
      uplink:       '上行 · 传感数据',
      downlink:     '下行 · 控制指令',
      // Representative operating-frequency bands, intentionally rounded.
      // Real ratios span ~3 orders of magnitude; see P0-2 for log discussion.
      freqHardware:     '1 – 10 kHz',
      freqControl:      '500 – 1000 Hz',
      freqLocalization: '100 – 400 Hz',
      freqPlanning:     '10 – 100 Hz',
      freqPerception:   '10 – 60 Hz',
      freqCoordination: '1 – 10 Hz',
    },
    pyramid: {
      panelTitle: '频率金字塔',
      ringControl:    '控制环 · 内',
      ringPlanning:   '规划环 · 中',
      ringPerception: '感知环 · 外',
      // Footer note: visual rotation speeds are proportional to the true
      // frequency ratio (control ≈ 33× perception). Without a note the
      // viewer might assume the pyramid's visual blur is artistic.
      note: '转速反映真实频率比 · 控制环约 33× 感知环',
    },
    coupling: {
      panelTitle:    '模块耦合',
      nodesTitle:    '节点',
      detailTitle:   '节点详情',
      hintIdle:      '点击节点 · 查看输入与输出',
      selected:      '已选中',
      inputs:        '输入',
      outputs:       '输出',
      none:          '—',
      // Node role names — kept distinct from labels.layers.* which carry
      // the '层' suffix used by the autonomy-stack scene.
      perception:    '感知',
      localization:  '定位',
      planning:      '规划',
      control:       '控制',
    },
  },
  ch02: {
    explodedTitle:     '四旋翼组件',
    imuVibrationTitle: 'IMU 振动耦合',
    frame:     '机架',
    motor:     '电机',
    esc:       '电调',
    battery:   '电池',
    fc:        '飞控',
    imu:       'IMU',
    camera:    '相机',
    gnss:      'GNSS 天线',
    companion: '机载计算机',
    exploded: {
      // Parts carry a zh-CN name shown in the DOM callout and an EN gloss
      // shown in monospace under it. Matches the project's "Chinese + English
      // on first appearance" language policy.
      partsTitle:    '组件 · 9 件',
      stateTitle:    '状态',
      stateAssembled: '组装',
      stateExplode:   '展开中',
      stateHold:      '展开保持',
      stateReform:    '复位中',
      hint:           '自动循环 · 点击画面暂停',
      hintResume:     '已暂停 · 点击画面继续',
      partCount:      '组件数',
      frameEn:     'Frame',
      motorEn:     'Motor ×4',
      escEn:       'ESC ×4',
      batteryEn:   'Battery',
      fcEn:        'Flight Controller',
      imuEn:       'IMU',
      cameraEn:    'Stereo Camera',
      gnssEn:      'GNSS Antenna',
      companionEn: 'Companion Computer',
    },
    vibration: {
      // Sliders + readouts for the split-screen vibration demo.
      controlsTitle: '控制',
      rpm:           '转速',
      cutoff:        '截止频率',
      rotorFreq:     '转子频率',
      snr:           '信噪比',
      rawTitle:      '原始 IMU · a(t)',
      filteredTitle: '一阶低通滤波后',
      rawAxis:       '加速度 / m·s⁻²',
      legendRaw:     '原始信号',
      legendFilt:    '滤波后',
      legendGravity: '重力基线',
      note:          '信号模型：a(t) = g + A·sin(2πf·t) + n(t)',
    },
  },
  ch03: {
    underactuationTitle: '欠驱动演示',
    pidTitle:            'PID 阶跃响应',
    se3Title:            'SE(3) 几何控制',
    underactuation: {
      // Top-left / top-right panels. The point: 6 DoF in pose, 4 independent
      // inputs. The right-panel "输入" count never climbs past 4 no matter what
      // motion the drone is asked to perform.
      dofPanel:     '自由度 · 位姿',
      inputPanel:   '控制输入',
      logPanel:     '控制日志',
      dofCount:     '6',
      inputCount:   '4',
      dofTransX:    '±X · 横移',
      dofTransY:    '±Y · 升降',
      dofTransZ:    '±Z · 前后',
      dofRotRoll:   '滚转 · φ',
      dofRotPitch:  '俯仰 · θ',
      dofRotYaw:    '偏航 · ψ',
      inputThrust:  '总推力 T',
      inputMRoll:   'M 滚转 · τφ',
      inputMPitch:  'M 俯仰 · τθ',
      inputMYaw:    'M 偏航 · τψ',
      // Phase banner + running log lines. Log lines are keyed so the sim
      // state machine can push them at phase transitions.
      stage1Title:  '阶段一 · 请求水平位移',
      stage2Title:  '阶段二 · 倾斜后再加速',
      goalTag:      '目标',
      tryTag:       '尝试',
      resultTag:    '结果',
      goalLateral:  '沿 +X 方向位移 1.5 m',
      tryThrustOnly:'仅增加总推力 T',
      failInfeasible:'✗ 欠驱动 · 水平无分量',
      pitchTilt:    '施加 M 俯仰 → 机体前倾',
      thrustTilt:   '倾斜推力 → 获得水平分量',
      levelOff:     '反向俯仰 → 恢复水平',
      succeed:      '✓ 到位 · 四入产生六动',
      hint:         '固定 3/4 视角 · 13 s 循环',
      thrustArrow:  '推力矢量 T',
    },
    pid: {
      panelTitle:    '二阶高度环',
      targetLabel:   '目标高度',
      altitudeLabel: '实测高度',
      altitudeChart: '高度 z(t)',
      contribP:      'P · 比例',
      contribI:      'I · 积分',
      contribD:      'D · 微分',
      kpLabel:       'K_p',
      kiLabel:       'K_i',
      kdLabel:       'K_d',
      presetP:       '仅 P',
      presetPD:      'P + D',
      presetPID:     'PID',
      overshootLabel:'超调',
      settleLabel:   '稳定时间',
      ssErrorLabel:  '稳态误差',
      resetHint:     '调节滑块 · 仿真自动重启',
      plantNote:     '被控对象：m·z̈ = T − m·g · m = 1 kg · g = 9.81',
      targetUnit:    'm',
      timeUnit:      's',
    },
    se3: {
      title:         'SE(3) 几何控制',
      subtitle:      '姿态误差活在流形上',
      currentPanel:  '当前姿态 R',
      desiredPanel:  '期望姿态 R_d',
      errorPanel:    'so(3) 误差',
      axisLabel:     '轴',
      angleLabel:    '角度',
      normLabel:     '‖e_R‖',
      rollLabel:     '滚转 φ',
      pitchLabel:    '俯仰 θ',
      yawLabel:      '偏航 ψ',
      hint:          '每 6 s 随机重采样 R_d',
      formula:       'e_R = ½ (R_dᵀ R − Rᵀ R_d)∨',
      bodyAxis:      '机体系三轴',
      desiredAxis:   '期望三轴',
      errorAxis:     '误差旋转轴',
    },
  },
  ch04: {
    imuDriftTitle: 'IMU 漂移 vs 卡尔曼融合',
    vioTitle:      'VIO 特征跟踪',
    slamTitle:     'SLAM 闭环校正',
    imuDrift: {
      // P0-7. Three drones fly the same ellipse. Truth is analytical; the
      // pure-IMU drone double-integrates a biased + noisy accelerometer;
      // the fused drone runs three independent 2-D Kalman filters (one per
      // world axis) using the IMU as a 200 Hz prediction and a 1 Hz GPS-like
      // position fix as the correction.
      filterPanel:   '估计器',
      errorPanel:    '位置误差',
      chartTitle:    '位置误差 / 时间',
      truthLabel:    '真值',
      imuLabel:      '纯 IMU',
      fusedLabel:    '融合',
      truthLegend:   '参考轨迹 · 真值',
      imuLegend:     '纯 IMU 积分 · 漂移',
      fusedLegend:   '卡尔曼融合 · 有界',
      gpsLegend:     'GPS 测量 · 1 Hz',
      imuRate:       'IMU 频率',
      gpsRate:       'GPS 频率',
      gpsNoise:      'GPS σ',
      stateDim:      '状态维度',
      note:          'IMU 偏置 → 二次积分发散 · GPS 1 Hz 修正使误差有界',
      hint:          '30 s 循环 · 偏置与噪声每周期重采样',
    },
    vio: {
      // P0-8. Drone orbits a central pillar while its onboard camera tracks
      // ~50 features (sparse colored points scattered across box faces,
      // ground, and air). The onboard view is rendered live; per-feature
      // optical-flow polylines are drawn as a DOM canvas overlay over that
      // viewport. A handful of features fail mid-loop to show VIO isn't
      // perfect.
      onboardLabel:  '机载相机',
      externalLabel: '外部视角',
      trackerPanel:  '特征跟踪',
      stateLabel:    '状态',
      tracked:       '跟踪中',
      reproj:        '重投影误差',
      total:         '场景特征',
      lost:          '已丢失',
      legendActive:  '活跃跟踪',
      legendFailing: '失效闪烁',
      legendFlow:    '光流轨迹 · 8 帧',
      note:          '机载相机 + IMU → VIO · 帧间特征匹配恢复运动',
      hint:          '20 s 循环 · 随机失效模拟跟踪丢失',
    },
  },
  ch05: {
    searchTitle:    'A*/RRT* 搜索扩展',
    minSnapTitle:   '最小 Snap 轨迹',
    corridorTitle:  '安全飞行走廊',
    search: {
      // Two algorithms run back-to-back in a loop: A* first (grid fill with
      // f-score gradient), then RRT* (random tree). Each phase ends in a
      // path reveal where the drone flies the result.
      algoPanel:     '当前算法',
      statsPanel:    '统计',
      legendPanel:   '图例',
      hintBL:        '15 s 扩展 + 5 s 飞行 · 算法循环',
      algoAStar:     'A* · 网格搜索',
      algoRRT:       'RRT* · 随机树',
      phaseExpand:   '扩展中',
      phaseReveal:   '路径生成',
      phaseFly:      '执飞',
      nodes:         '节点探索',
      pathLen:       '路径长度',
      iters:         '迭代',
      legendStart:   '起点',
      legendGoal:    '终点',
      legendObs:     '障碍',
      legendPath:    '最终路径',
      legendOpen:    '待扩展',
      legendClosed:  '已扩展',
      legendTree:    '随机树',
      noteAStar:     '启发式 · 欧式距离 · 8 连通',
      noteRRT:       '步长 1.5 m · 重接半径 1.8 m',
    },
    minSnap: {
      // Two-mode demo that flips between piecewise-linear "naive" routing and
      // a 7th-order polynomial spline that is C^6 continuous (uniquely
      // determined → mathematically equivalent to minimum-snap when segment
      // times are fixed). Side panels chart |a| and |jerk| to make the lurch
      // vs. flow contrast quantitative.
      modePanel:     '模式',
      statsPanel:    '动态统计',
      hintBL:        '4 路径点 · 12 s 每模式 · 自动循环',
      modeNaive:     '直线连接',
      modeSnap:      '最小 Snap · 7 阶样条',
      legendNaive:   '直线轨迹',
      legendSnap:    '最小 Snap',
      legendActive:  '执飞',
      accelPeak:     '加速度峰值',
      jerkPeak:      '加加速度峰值',
      accelChart:    '|a(t)|',
      jerkChart:     '|j(t)|',
      timeAxis:      '时间 t / s',
      note:          '同等平均速度 · 同样路径点 · 不同轨迹平滑度',
    },
    corridor: {
      // The trajectory plans a coarse path through obstacles, the kit inflates
      // a chain of overlapping convex boxes around it (the "corridor"), and a
      // smoothed trajectory is then constrained to live inside the corridor.
      stagePanel:    '阶段',
      statsPanel:    '走廊统计',
      hintBL:        '直线 → 走廊 → 平滑轨迹',
      stage1:        '初始直线路径',
      stage2:        '膨胀凸多面体',
      stage3:        '约束平滑',
      stage4:        '执飞',
      boxCount:      '凸盒数',
      minClear:      '最小间隙',
      legendInit:    '初始路径',
      legendCorr:    '凸走廊',
      legendSmooth:  '平滑轨迹',
      note:          '将非凸避障松弛为凸约束',
    },
  },
  demo: {
    // Strings used only by src/kit-demo.html (Phase 0 acceptance test).
    title:     '工具包演示',
    telemetry: '遥测',
    sensors:   '传感器',
    lidarHits: '激光命中',
    trail:     '飞行轨迹',
    altChart:  '高度曲线',
  },
};
